name: Publish release
on: [repository_dispatch]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: npm install
        if: github.event.action == 'PUBLISH_RELEASE'
        run: npm install

      - name: Prepare NPM
        if: github.event.action == 'PUBLISH_RELEASE'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

      - name: Run release
        if: github.event.action == 'PUBLISH_RELEASE'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release

      - name: Cleanup
        run: rm -f .npmrc
