name: Publish release
on: [repository_dispatch]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Run release
        if: github.event.action == 'PUBLISH_RELEASE'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
